char sql_maptiers_create[] = 
"CREATE TABLE IF NOT EXISTS `maptiers` "...
	"(`map` VARCHAR(128), "...
	"`tier` INT NOT NULL DEFAULT %d, "...
	"`limitPrespeed` TINYINT(1) NOT NULL DEFAULT 1, "...
	"`maxvelocity` FLOAT NOT NULL DEFAULT %f, "...
	"PRIMARY KEY (`map`));";

char mysql_GetMapSettings[] = 
"SELECT tier, limitPrespeed, maxvelocity "...
	"FROM `maptiers` "...
	"WHERE map = '%s';";

char mysql_InsertMapSettings[] = 
"INSERT INTO `maptiers` "...
	"(map, tier, limitPrespeed, maxvelocity) VALUES "...
	"('%s', %d, 1, %f);";

char mysql_GetMapTier[] = 
"SELECT map, tier "...
	"FROM `maptiers`;";

char mysql_SetMapTier[] = 
"UPDATE `maptiers` SET tier = %d "...
	"WHERE map = '%s';";

char mysql_SaveMapSettings[] = 
"UPDATE `maptiers` SET "...
		"tier = %d, "...
		"limitPrespeed = %d, "...
		"maxvelocity = %f "...
	"WHERE map = '%s';";

char mysql_DeleteMapAllSettings[] = 
"DELETE FROM `maptiers` "...
	"WHERE map = '%s';";



char mysql_modify_default_maxvel[] = 
"ALTER TABLE `maptiers` MODIFY COLUMN "...
	"maxvelocity FLOAT NOT NULL DEFAULT %f;";