name: ci

on:
  push:
    paths-ignore:
    - LICENSE
    - README.md
  pull_request:
    paths-ignore:
    - LICENSE
    - README.md

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        sm_version: [ "1.11" ]


    steps:
      - uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          SCRIPTING_PATH=$GITHUB_WORKSPACE/addons/sourcemod/scripting
          INCLUDE_PATH=$GITHUB_WORKSPACE/addons/sourcemod/scripting/include
          GAMEDATA_PATH=$GITHUB_WORKSPACE/addons/sourcemod/gamedata
          EXT_PATH=$GITHUB_WORKSPACE/addons/sourcemod/extensions
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTING_PATH=$SCRIPTING_PATH" >> $GITHUB_ENV
          echo "INCLUDE_PATH=$SCRIPTING_PATH/include" >> $GITHUB_ENV
          echo "GAMEDATA_PATH=$GAMEDATA_PATH" >> $GITHUB_ENV
          echo "EXT_PATH=$EXT_PATH" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Download Requirements
        run: |
          echo -e "\nDownloading requirements..."

          wget https://github.com/rtldg/sm_closestpos/releases/download/v1.1.1/sm_closestpos-sm1.10-ubuntu-18.04-b0a9b88.zip
          mv sm_closestpos-sm1.10-ubuntu-18.04-b0a9b88.zip sm_closestpos-sm1.10-ubuntu.zip
          unzip -o sm_closestpos-sm1.10-ubuntu.zip
          rm -rf ./sm_closestpos-sm1.10-ubuntu.zip

          wget https://github.com/rtldg/sm_closestpos/releases/download/v1.1.1/sm_closestpos-sm1.10-windows-latest-b0a9b88.zip
          mv sm_closestpos-sm1.10-windows-latest-b0a9b88.zip sm_closestpos-sm1.10-windows.zip
          unzip -o sm_closestpos-sm1.10-windows.zip
          rm -rf ./sm_closestpos-sm1.10-windows.zip

          git clone https://github.com/GAMMACASE/MomSurfFix.git
          cp -r MomSurfFix/addons ./
          rm -rf ./MomSurfFix

          git clone https://github.com/jason-e/rngfix.git
          cp -r rngfix/plugin/* ./addons/sourcemod/
          rm -rf ./rngfix

          git clone https://github.com/GAMMACASE/HeadBugFix.git
          cp -r HeadBugFix/addons ./
          rm -rf ./HeadBugFix
      - name: Compile shavit plugin
        run: |
          echo -e "\nCompiling shavit plugins..."
          ls
          spcomp64 -O2 -i ./include eventqueuefix.sp
          spcomp64 -O2 -i ./include shavit-chat.sp
          spcomp64 -O2 -i ./include shavit-checkpoints.sp
          spcomp64 -O2 -i ./include shavit-core.sp
          spcomp64 -O2 -i ./include shavit-hud.sp
          spcomp64 -O2 -i ./include shavit-misc.sp
          spcomp64 -O2 -i ./include shavit-paint.sp
          spcomp64 -O2 -i ./include shavit-replay-playback.sp
          spcomp64 -O2 -i ./include shavit-replay-recorder.sp
          spcomp64 -O2 -i ./include shavit-sounds.sp
          spcomp64 -O2 -i ./include shavit-stats.sp
          spcomp64 -O2 -i ./include shavit-tas.sp
          spcomp64 -O2 -i ./include shavit-timelimit.sp
          spcomp64 -O2 -i ./include shavit-wr.sp
          spcomp64 -O2 -i ./include shavit-zones.sp
          mkdir ../plugins && mv ./*.smx ../plugins
        working-directory: ${{ env.SCRIPTING_PATH }}/

      - name: Compile Requirements
        run: |
          echo -e "\nCompiling required plugins..."
          spcomp64 -O2 -i ./include momsurffix2.sp
          spcomp64 -O2 -i ./include rngfix.sp
          spcomp64 -O2 -i ./include headbugfix.sp
          mv ./*.smx ../plugins
        working-directory: ${{ env.SCRIPTING_PATH }}/

      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        with:
          name: bhoptimer-${{ env.GITHUB_SHA_SHORT }}
          path: ./
